import type { LexiconDef } from '../types'

export const lexicons: LexiconDef[] = [
  {
    id: 'lex-proof',
    color: 'teal',
    description:
      "Anchors a digital artifact to an AT Protocol DID via content-addressable hash. The creator's repo commit signature constitutes the attestation of authorship.",
    recordKey: 'tid — a timestamp-derived ID generated by the PDS at record creation time.',
    sections: [
      {
        title: 'Fields',
        fields: [
          { name: 'artifactCid', type: 'string', required: true, description: 'CID (DAG-CBOR, base32 multibase) of the artifact. Computed over raw artifact bytes. Max 512 chars.' },
          { name: 'algorithm', type: 'string', required: true, description: 'Hash algorithm. Known values: sha2-256, blake3. blake3 preferred where supported.' },
          { name: 'signerDid', type: 'did', required: true, description: 'DID of the entity asserting authorship. MUST match the repo DID where this record is stored.' },
          { name: 'mimeType', type: 'string', required: true, description: 'IANA media type of the artifact (e.g. image/png, video/mp4). Max 128 chars.' },
          { name: 'createdAt', type: 'datetime', required: true, description: 'ISO 8601 datetime the creator asserts the artifact was produced. May differ from the record\'s indexed timestamp.' },
          { name: 'title', type: 'string', description: 'Optional human-readable title. Not used in hash computation. Max 300 chars.' },
          { name: 'description', type: 'string', description: 'Optional description. Not used in hash computation. Max 3000 chars.' },
          { name: 'metadataUri', type: 'uri', description: 'Optional pointer to extended metadata. May be an AT URI or HTTPS URL. Not authoritative — the CID is. Max 2048 chars.' },
          { name: 'previousProofUri', type: 'at-uri', description: 'Optional AT URI of a prior proof for this artifact. Use when re-attesting after a DID rotation or key migration.' },
        ],
      },
      {
        title: 'Example record',
        example: `{
  "$type": "at.ofwork.proof",
  "artifactCid": "bafyreihfsnz5qtbpf4kkpbwp46fafj6j5l3dh6ib6xz4dn2mhm5odnjq4",
  "algorithm": "sha2-256",
  "signerDid": "did:plc:abc123examplecreator",
  "mimeType": "image/png",
  "title": "Untitled No. 7",
  "createdAt": "2025-03-14T09:00:00.000Z"
}`,
      },
    ],
  },
  {
    id: 'lex-purchase',
    color: 'purple',
    description:
      'Verifiable attestation that a buyer DID acquired a specific artifact from a seller DID. Written by the seller into their own repo.',
    recordKey: 'tid — generated by the PDS at record creation time.',
    sections: [
      {
        title: 'Fields',
        fields: [
          { name: 'proofRef', type: 'strongRef', required: true, description: 'Immutable strong reference (AT URI + CID) to the at.ofwork.proof record identifying the artifact being sold.' },
          { name: 'buyerDid', type: 'did', required: true, description: 'DID of the acquiring entity. Any resolvable DID method is acceptable.' },
          { name: 'sellerDid', type: 'did', required: true, description: 'DID of the entity conducting the sale. MUST match the DID of the AT Proto repo where this record is stored.' },
          { name: 'price', type: 'object', required: true, description: 'Denomination and amount paid. See #price type below. Use amount "0" for complimentary transfers.' },
          { name: 'purchasedAt', type: 'datetime', required: true, description: 'ISO 8601 datetime of transaction completion. Should reflect payment confirmation time.' },
          { name: 'transactionId', type: 'string', description: 'Optional opaque external payment reference (Stripe charge ID, Lightning hash, on-chain tx hash). Max 512 chars.' },
          { name: 'platform', type: 'uri', description: 'Optional URI identifying the marketplace or application where the sale was conducted. Max 2048 chars.' },
          { name: 'note', type: 'string', description: 'Optional seller-authored note (e.g. edition number, fulfilment detail). Not a legal document. Max 1000 chars.' },
        ],
      },
      {
        title: 'The #price type',
        fields: [
          { name: 'amount', type: 'string', required: true, description: 'Decimal string to avoid floating-point precision loss. Examples: "9.99", "0". Negative values not permitted. Max 32 chars.' },
          { name: 'currency', type: 'string', required: true, description: 'ISO 4217 fiat code (USD, EUR) or token identifier (USDC, ETH). Max 20 chars.' },
        ],
      },
      {
        title: 'Example record',
        example: `{
  "$type": "at.ofwork.purchase",
  "proofRef": {
    "uri": "at://did:plc:abc123examplecreator/at.ofwork.proof/3juqv7yxhm22h",
    "cid": "bafyreihfsnz5qtbpf4kkpbwp46fafj6j5l3dh6ib6xz4dn2mhm5odnjq4"
  },
  "buyerDid": "did:plc:xyz789examplebuyer",
  "sellerDid": "did:plc:abc123examplecreator",
  "price": { "amount": "25.00", "currency": "USD" },
  "transactionId": "ch_3OxampleStripeCharge",
  "purchasedAt": "2025-03-15T14:22:00.000Z"
}`,
      },
    ],
  },
  {
    id: 'lex-consent',
    color: 'coral',
    description:
      'Records the licensing terms granted to a buyer at the time of purchase. Always subordinate to a purchase record — a consent without a valid purchase is semantically invalid.',
    recordKey: 'tid — generated by the PDS at record creation time.',
    sections: [
      {
        title: 'Fields',
        fields: [
          { name: 'purchaseRef', type: 'strongRef', required: true, description: 'Immutable strong reference (AT URI + CID) to the at.ofwork.purchase this consent accompanies.' },
          { name: 'licenseType', type: 'string (token)', required: true, description: 'Well-known license token. Known values: all-rights-reserved, cc-by-4.0, cc0-1.0, custom, and CC variants.' },
          { name: 'scope', type: 'string[]', required: true, description: 'Permitted-use categories. Absence means that use is NOT granted. Values: personal, commercial, editorial, broadcast, derivative, ai-training, resale.' },
          { name: 'transferable', type: 'boolean', required: true, description: 'Whether the buyer may assign or sublicense these rights to a third party.' },
          { name: 'grantedAt', type: 'datetime', required: true, description: 'ISO 8601 datetime of the license grant. Should match or closely follow purchasedAt.' },
          { name: 'licenseUri', type: 'uri', description: 'Required when licenseType is "custom". MUST point to immutable license text. Prefer content-addressed URIs. Max 2048 chars.' },
          { name: 'territory', type: 'string', description: 'ISO 3166-1 alpha-2 country code, or "worldwide". Omit to default to worldwide. Max 64 chars.' },
          { name: 'expiresAt', type: 'datetime', description: 'Optional expiry. Omit for perpetual grants. Verifiers MUST treat expired consents as invalid.' },
          { name: 'revocationUri', type: 'uri', description: 'Optional revocation status endpoint. A 200 response with body "valid" means in force; any other response indicates revocation.' },
          { name: 'conditions', type: 'string', description: 'Optional plain-text additional conditions. Human-readable only. Max 2000 chars.' },
        ],
      },
      {
        title: 'Example record',
        example: `{
  "$type": "at.ofwork.consent",
  "purchaseRef": {
    "uri": "at://did:plc:abc123examplecreator/at.ofwork.purchase/3k2mv8abcd11x",
    "cid": "bafyreid7f3mhm5odnjq4snz5qtbpf4kkpbwp46fafj6j5l3dh6ib6xz4d"
  },
  "licenseType": "all-rights-reserved",
  "scope": ["personal", "editorial"],
  "territory": "worldwide",
  "transferable": false,
  "grantedAt": "2025-03-15T14:22:05.000Z"
}`,
      },
    ],
  },
  {
    id: 'lex-aipolicy',
    color: 'amber',
    description:
      'Creator-issued machine-readable preferences for AI/ML consumption of a specific artifact. Stored as a sibling to the proof, not embedded in it. Revocable by deletion.',
    recordKey: 'tid — generated by the PDS at record creation time.',
    sections: [
      {
        title: 'Revocation model',
        fields: undefined,
      },
      {
        title: 'Fields',
        fields: [
          { name: 'proofRef', type: 'strongRef', required: true, description: 'Immutable strong reference (AT URI + CID) to the at.ofwork.proof this policy applies to. Repo DID MUST match the proof\'s signerDid.' },
          { name: 'trainingAllowed', type: 'string (token)', required: true, description: 'Whether this artifact may be used in AI/ML training datasets. Values: yes, no, conditional.' },
          { name: 'inferenceAllowed', type: 'string (token)', required: true, description: 'Whether AI systems may use this artifact during inference (RAG context, few-shot examples, style references). Values: yes, no, conditional.' },
          { name: 'createdAt', type: 'datetime', required: true, description: 'ISO 8601 datetime. Tiebreaker when multiple records exist for the same proof — latest wins.' },
          { name: 'indexingAllowed', type: 'string (token)', description: 'Whether AI crawlers may index this artifact. Values: yes, no. Defaults to yes if omitted.' },
          { name: 'generativeOutputAllowed', type: 'string (token)', description: 'Whether AI may produce outputs stylistically derived from this artifact. Values: yes, no, conditional. Defaults to no.' },
          { name: 'trainingConditions', type: 'string', description: 'Required when trainingAllowed is "conditional". Plain-text conditions for training use. Max 2000 chars.' },
          { name: 'inferenceConditions', type: 'string', description: 'Required when inferenceAllowed is "conditional". Plain-text conditions for inference use. Max 2000 chars.' },
          { name: 'optOutRegistries', type: 'uri[]', description: 'Optional URIs to external AI opt-out registries. Informational — structured fields are authoritative. Max 10 entries.' },
          { name: 'robotsTxtEquivalent', type: 'string', description: 'Optional robots.txt-style directive string. Informational only — structured fields are authoritative. Max 500 chars.' },
        ],
      },
      {
        title: 'Example — restrictive policy',
        example: `{
  "$type": "at.ofwork.aiPolicy",
  "proofRef": {
    "uri": "at://did:plc:abc123examplecreator/at.ofwork.proof/3juqv7yxhm22h",
    "cid": "bafyreihfsnz5qtbpf4kkpbwp46fafj6j5l3dh6ib6xz4dn2mhm5odnjq4"
  },
  "trainingAllowed": "no",
  "inferenceAllowed": "no",
  "indexingAllowed": "yes",
  "generativeOutputAllowed": "no",
  "optOutRegistries": ["https://haveibeentrained.com/optout"],
  "createdAt": "2025-03-14T09:05:00.000Z"
}`,
      },
      {
        title: 'Example — conditional training',
        example: `{
  "$type": "at.ofwork.aiPolicy",
  "proofRef": {
    "uri": "at://did:plc:abc123examplecreator/at.ofwork.proof/3juqv7yxhm22h",
    "cid": "bafyreihfsnz5qtbpf4kkpbwp46fafj6j5l3dh6ib6xz4dn2mhm5odnjq4"
  },
  "trainingAllowed": "conditional",
  "trainingConditions": "Non-commercial academic research only. Attribution required.",
  "inferenceAllowed": "yes",
  "indexingAllowed": "yes",
  "generativeOutputAllowed": "no",
  "createdAt": "2025-03-14T09:05:00.000Z"
}`,
      },
    ],
  },
]
